cloudius-systems/osv

Makefile
arch/aarch64/arch-dtb.cc
arch/aarch64/arch-dtb.hh
arch/aarch64/arch-mmu.hh
arch/aarch64/arch-setup.cc
arch/aarch64/boot.S
arch/aarch64/early-console.cc
arch/aarch64/early-console.hh
arch/aarch64/hypercall.S
arch/aarch64/preboot.S
arch/aarch64/xen.cc
arch/aarch64/xen.hh
bsd/aarch64/machine/xen/hypercall.h
bsd/sys/xen/hypervisor.h
bsd/sys/xen/interface/arch-aarch64.h
bsd/sys/xen/interface/xen.h
compiler/include/intrinsics.hh
drivers/xenconsole.cc
drivers/xenconsole.hh

hi OSv developers,
Here let me present you with second version of patches to allow OSv kernel to be loaded
under Xen hypervisor on AARCH64 platform.
previous discussion is here:
https://groups.google.com/forum/#!topic/osv-dev/15G00wWkB-s
Changes since initial RFC version:
- added comments clarifying preboot header
- fixed typos in commit msgs
- use is_xen() macro instead of bool is_xen_found flag
- reworked patch to detect hypervisor at runtime and choose console accordingly
This is basic stuff, which allows to initialise kernel and see log messages.
No SMP support yet, no heavy PV drivers yet and no application can be run.
Verified on Renesas R-Car board [1] and on qemu-aarch64 (for not to break anything)
[1] http://elinux.org/R-Car/Boards/Salvator-X

[RFC][V2] aarch64: basic Xen support

---

scripts/download_rpm_package.sh

Since the script was originally written, a few things such as
* location of the Fedora repositories
* format of HTML page
has changed. This leads to errors when setting up cross build
environment for arm64.
Fix these issues by updating the repo url and the regular expression
used to parse the package version.
Note: The mechanism to download the packages is a little fragile and
may break again in the future. Hopefully, all this can go away once
the build system has been migrated to use the native distro packages.
Signed-off-by: Punit Agrawal <pagrawal@lynx.com>
Closes: #1103

scripts: Update script to download RPM packages

---

scripts/run.py

The problem happens when XEN is the provider configured on the server.
I was running `./scripts/build image=openjdk8-zulu-full,spring-boot-example` and I got this error:
```
Saving command line to /home/inacio/osv/build/release.x64/cmdline
Building into build/release.x64
GEN gen/include/osv/version.h
Traceback (most recent call last):
File "scripts/run.py", line 637, in <module>
cmdargs.hypervisor = choose_hypervisor(cmdargs.networking,cmdargs.arch)
File "scripts/run.py", line 502, in choose_hypervisor
and 'control_d' in file('/proc/xen/capabilities').read()
NameError: name 'file' is not defined
Traceback (most recent call last):
File "/home/inacio/osv/scripts/upload_manifest.py", line 170, in <module>
main()
File "/home/inacio/osv/scripts/upload_manifest.py", line 160, in main …
```

fixed NameError: name 'file' is not defined

---

drivers/pci-device.cc
drivers/pci-function.cc
drivers/pci-function.hh

When computing the size of a BAR the device should not try to decode the content of the BAR as an address. For example, this can cause a crash in QEMU trying to map memory at a nonexistent address.

Disable BARs decoding when computing size

---

drivers/pci-function.cc

When using the `interrupt_manager::easy_register()` function multiple times on a device (e.g., to register interrupts for multiple queue pairs in a virtio-net device), `msi(x)_enable()` is called multiple times, causing interrupts that have previously been registered to be masked and never unmasked. Avoid this problem by preventing  the execution of `msi[x]_enable()` if msi[x] is already enabled.

pci: avoid execution of msix_enable() function if already enabled

---

scripts/build-capstan-base-image

Whenever I build a base image on an amd64 system with `scripts/build` and I build it with `./scripts/build-capstan-base-image openjdk17 openjdk9_1x-from-host`, it fails with:
```sh
+ cp build/release/osv.qcow2 /root/.capstan/repository/papermc/papermc.qemu
cp: cannot stat 'build/release/osv.qcow2': No such file or director
```
This fix uses the same method as used in `./scripts/convert` to determine where to find the last build.

Add support for release.x64 directory in build-capstan-base-image

---

libc/mman.cc
linux.cc
modules/tests/Makefile
tests/tst-brk.c

This patch implements the program break and the related functions `brk()` and `sbrk()` and the corresponding syscall. The program counter implementation is necessary to support statically linked executables as well as applications launched by the Linux dynamic linker (aka `ld-linux-x86-64.so.2`) on OSv.
Please note that both the functions and the syscall are considered legacy API however we need to support it for the reasons stated above. Glibc and some memory allocators like **jemalloc** use `brk` for some type of memory allocations. 
In essence, the program break implementation is based on `mmap()`. For details please look into the relevant code comments.
This patch also adds a new unit test to verify if the program break works correctly.
This is one of the very first patches of the …

brk/sbrk: implement program break

---

bsd/sys/kern/uipc_socket.cc
include/osv/poll.h
libc/af_local.cc
libc/pipe_buffer.cc
libc/pipe_buffer.hh
tests/tst-epoll.cc

[poll: drop POLLINIGNEOF and fix POLLRDHUP](https://github.com/cloudius-systems/osv/commit/67eab5e0b1924c59275a34a9a7af626e7f0a2f89) 
Both POLLIGNEOF and POLLRDHUP use the same value. POLLRDHUP must
be congruent to EPOLLRDHUP, so it can't change. However, POLLIGNEOF is
unused so extirpate POLLINIGNEOF from the code base.
Also, update sopoll_generic_locked so that POLLRDHUP can actually
be set when requested by clients.
Finally, add support of EPOLLRDHUP in AF_LOCAL sockets

poll: drop POLLINIGNEOF and fix POLLRDHUP

---

scripts/pull_github_pr.sh

Although github pull requests are convenient way to track pending patches and to review small or large patch sets, it's not obvious for maintainers how to try such PRs locally, and also when eventually deciding to merge the PR, github provides a "merge" button in its GUI with multiple problems:
1. It often botches the committer's address
2. It "merges" even single-patch PRs. This is not OSv's tradition - single patches should remain a single patch, not a merge of a single-patch branch.
The script in this patch, scripts/pull_github_pr.sh, solves both problems: If the maintainer runs,
scripts/pull_github_pr.sh 1245
Fetches PR number 1245 locally, you can then compile and test it yourself, and if you're pleased, finally push it.
A complete session may look something like this:
```
git …
```

Add script for merging a github pull request

---

arch/aarch64/arch-elf.cc
arch/aarch64/arch-switch.hh
arch/x64/arch-elf.cc
arch/x64/arch-switch.hh
core/elf.cc
include/osv/elf.hh

The two commits provide necessary modifications to the OSv dynamic linker to support loading and processing statically linked executables.
Please note these changes are NOT enough to make OSv run statically linked executables.

Dynamic linker: support loading and processing statically linked executables

---

Makefile
include/api/stdlib.h
libc/sem.cc
libc/stdlib/unimplemented.cc
modules/tests/Makefile
scripts/setup.py
tests/tst-align.cc
tests/tst-f128.cc

This this small series we fix what needs to be fixed to build OSv on Fedora 38:
1. Update setup.py to allow Fedora 38
2. Add two stub functions that new libstdc++ started to need (but it's fine that they are stub)
3. Add a missing include directive
After this patch, the OSv kernel builds and also some images (e.g., "rogue"). The default (Lua shell) build builds but doesn't run and will need to be fixed later.
Fixes #1238.

Fix build for Fedora 38

---

linux.cc

Unlike the libc `exit()` function, the system call exit in Linux is supposed to terminate the current thread. This patch fixes the current incorrect implementation that delegates to `exit()`.

syscalls: make exit terminate current thread

---

arch/aarch64/arch-elf.hh
arch/x64/arch-elf.hh
core/app.cc
core/elf.cc
include/osv/app.hh
include/osv/elf.hh

This patch enhances the dynamic linker to support launching statically linked executables.
The dynamically linked executables or shared libraries are typically launched by calling a "main" function which is exported and can be resolved using the ELF symbol table. The statically linked executables do not export
such symbols and instead must be launched by jumping to the ELF entry point specified in the header. To that end this patch implements new functions - `run_entry_point()` - specific for each architecture - x86_64 and aarch64 which fundamentally do a similar thing - put `argc`, `argv`, environment variables, and auxiliary vector on the stack and jump to the elf entry point.
In addition, this patch enhances other parts of the dynamic linker logic to do things a little bit differently …

core: support launching statically linked executables

---

arch/aarch64/arch-switch.hh
arch/x64/arch-cpu.hh
arch/x64/arch-switch.hh
arch/x64/arch-thread-state.hh
arch/x64/arch-tls.hh
arch/x64/msr.hh
arch/x64/syscall.S
arch/x64/syscall.hh
core/sched.cc
include/osv/sched.hh

The original syscall implementation utilized the TCB (Thread Control Block) to store the syscall stack address. On each context switch, the FS segment register would be reset to point to the thread-specific TCB where syscall handler would fetch its stack address.
In order to support statically linked executables that allocate and use their own TCB, OSv needs to be able to switch the FS register between the user and kernel address when handling syscalls. The syscall handler can no longer fetch its stack address from kernel TCB because the FS register points to the app TCB. In order to break this dependency, this patch changes all relevant code to move the syscall stack address and syscall caller stack pointer to the per-CPU memory area addressed by the GS segment register.
To that end, we …

syscall: use GS register to store syscall stack address

---

Makefile
core/strace.cc
core/trace.cc
include/osv/strace.hh
include/osv/trace.hh
loader.cc

This PR implements a simple strace-like mechanism described by https://github.com/cloudius-systems/osv/issues/1263.
In essence, it adds a new structure trace_log that holds a fixed size (64K)
an array of pointers to trace_records and acts as a ring buffer between threads
capturing active tracepoints (producers) and new thread strace (single consumer)
that prints them to the console. The write pointer - write_offset - is atomic that
rolls over every 64K and the strace thread follows it and tries to print
each trace (see print_trace).
The strace can be activated by adding "--strace" kernel command line argument.
```bash
./scripts/firecracker.py -e '--trace=vfs* --strace /hello'
OSv v0.57.0-75-gb7150705
init              0  0.001666500 vfs_mkdir("/dev" 0755)
init              0  0.001685758 …
```

Add strace functionality

---

libc/signal.cc
libc/signal.hh

In theory, it would not matter how we encode the information about which signals are masked as long as our implementation of it stays completely internal. But in reality, when we implement rt_sigprocmask and other related syscalls, the users of those like glibc rely on the format of the bitmask used by Linux kernel. In Linux, the least significant bit (or the most right) represents the mask of the signal number 1, the 2nd bit represents the mask of the signal number 2, etc all the way to the maximum number 64. So we must ensure that our internal sigset structure can fit all these 64 bits and nothing more as some runtimes like golang assume the oldset argument of the rt_sigprocmask can be as small as NSIG/8 (8 bytes).
To get or set a specific signal mask bit, we simply substract 1 from the …

signals: make signal mask layout match Linux

---

core/app.cc
core/elf.cc
include/osv/elf.hh

This PR enhances OSv to be able to launch dynamically linked executables(PIEs or non-PIEs) using the Linux dynamic linker - `ld-linux-x86-64.so.2` on x86_64 or `ld-linux-aarch64.so.1` on aarch64 like so:
```bash
./scripts/run.py -e '/lib64/ld-linux-x86-64.so.2 /hello'
```
The motivation is to allow running dynamically linked executables that depend on the libc symbols not implemented by the OSv kernel. In this case, the executables launched this way would interact only through system calls just like the statically linked ones do. Actually, my experiments so far seem to show that there are no extra changes needed beyond the same code enhancements to support statically linked executables.
When executing a dynamically linked executable, Linux reads the `PT_INTERP` segment to determine the …

Support executing dynamically-linked executables via Linux dynamic linker

---

Makefile
arch/x64/arch-cpu.hh
arch/x64/arch-switch.hh
arch/x64/arch-tls.hh
arch/x64/entry.S
arch/x64/prctl.cc
arch/x64/tls-switch.hh
core/elf.cc
include/osv/sched.hh
libc/vdso/vdso.cc
libc/vdso/vdso.lds
linux.cc

Even the simplest executables need thread-local storage (TLS) and a good example of it is `errno` which is a thread-local variable. The OSv kernel itself uses many thread-local variables and when running dynamically linked executables it shares the TLS memory block with the application. In this case, OSv fully controls the setup of TLS and it stores the pointer to TCB (Thread Control Block) as part of a thread state and updates the FS register on every context switch.
On the other hand, the statically linked executables set up their TLS and register it with the kernel by executing syscall `arch_prtcl` on x86_64. In order to support it in OSv, we need to implement the `arch_prtcl` syscall and modify some key places in kernel code - syscall handler, exception handlers, and VDSO - to switch …

Implement arch_prctl syscall to support TLS in statically linked executables

---

Makefile
arch/x64/arch-switch.hh
arch/x64/clone.cc
core/sched.cc
include/osv/sched.hh
linux.cc

This PR implements `clone`, `clone3`, `set_robust_list`, and `set_tid_address` syscalls needed to support running multi-threaded static executables on OSv.
The bulk of this patch is the implementation of the `clone` and its `clone3` variant. More specifically the `sys_clone()` implements only the tiny subset of what the Linux manual describes - handling of `CLONE_THREAD` - which is what is used by glibc to implement `pthread_create()`.
In essence, the `sys_clone()` creates a new thread, sets application TCB if present, and then when started new thread executes code implemented in assembly to restore most of the registers and jump to the instruction where the parent thread calling clone would execute next. So effectively a thread calling the clone syscall would "clone" itself by creating a …

implement clone/3, set_robust_list and set_tid_address syscalls

---

fs/vfs/main.cc
linux.cc

This patch adds tracepoints for the syscalls implemented in `linux.cc`. The new tracepoints capture both the arguments and return value. The format is somewhat similar to Linux strace where the return value is first like so:
TRACEPOINT(trace_syscall_open, "%d <= \"%s\" 0x%x", int, const char *, int);
Having both input and output captured by one single tracepoint instead of two makes it easier to observe things using the new OSv strace capability.
With strace enabled, one can observe what syscalls application makes like in this example:
```bash
./scripts/run.py -e '--strace --trace=syscall\* /httpserver.so' OSv v0.57.0-76-g76e30467
eth0: 192.168.122.15
Booted up in 134.48 ms
Cmdline: /httpserver.so
/httpserver.so    0  0.099321648 syscall_sys_sched_getaffinity(8 <= 0 8192 0x2000001fef10) …
```

add syscall tracepoints

---

core/waitqueue.cc
tests/tst-wait-for.cc

As issue #1285 describes, the following edge condition is not handled correctly and results in a crash:
1. wo_older.arm() //(of wait_object<waitqueue> type)
2. wo_newer1.arm()
3. wo_older.disarm()
4. wo_newer2.arm() // Crash would happen here
5. wo_newer1.disarm()
6. wo_newer2.disarm()
```
./scripts/run.py -e '/tests/tst-wait-for.so'
OSv v0.57.0-109-gcf0f7526
eth0: 192.168.122.15
Booted up in 180.05 ms
Cmdline: /tests/tst-wait-for.so
Running 8 test cases...
page fault outside application, addr: 0x0000000000000000 [registers]
RIP: 0x00000000403a18c1 <sched::wait_object<waitqueue>::arm()+17>
RFL: 0x0000000000010206  CS:  0x0000000000000008  SS:  0x0000000000000010 RAX: 0x00002000001ff770  RBX: 0x00002000001ff7f0  RCX: 0x0000000000000000  RDX: 0x0000000000000000 RSI: 0x0000600000fd4c00  RDI: …
```

waitqueue: fix edge condition in disarm()

---

libc/pthread.cc

The current implementations of `pthread_rwlock_trywrlock` and `pthread_rwlock_tryrdlock` don't follow the POSIX specification and return incorrect values. Fix the return values to follow the specification.

libc/pthread: Make pthread_rwlock_trywrlock/tryrdlock posix compatible

---

Makefile
fs/ext/ext_null_vfsops.cc
fs/vfs/vfs_conf.cc
modules/libext/.gitignore
modules/libext/Makefile
modules/libext/README.md
modules/libext/ext_vfsops.cc
modules/libext/ext_vnops.cc
modules/libext/module.py
modules/libext/test.sh
modules/lwext4/.gitignore
modules/lwext4/Makefile
modules/lwext4/usr.manifest

This commit adds an initial implementation of the ext4 filesystem driver based on the lwext4 project
(https://github.com/gkostka/lwext4). It provides a lightweight read-write alternative to the ZFS filesystem.
Please note this implementation is NOT thread-safe and will need to be enhanced to be so in the future. However, it is functional enough to support the test cases examined by `modules/libext/test.sh`.
One can build the OSv like so:
```bash
./scripts/manifest_from_host.sh -w /usr/bin/find && \
./scripts/build fs=rofs image=libext,native-example -j$(nproc) --append-manifest
```
Then create an ext4 filesystem:
```
mkdir -p ext_images
dd if=/dev/zero of=ext_images/ext4 bs=1M count=128 sudo mkfs.ext4 ext_images/ext4
```
Add some files to it if needed:
```
sudo losetup -o 0 -f --show …
```

ext4: add initial implementation

---

Makefile
drivers/ahci.cc
drivers/blk-common.cc
drivers/blk-common.hh
drivers/ide.cc
drivers/virtio-blk.cc
drivers/virtio-fs.cc
drivers/virtio-scsi.cc
drivers/vmw-pvscsi.cc
drivers/xenfront-blk.cc
include/osv/ioctl.h

This patch adds very basic `ioctl` support for block devices as described by #1315.
Fixes #1315

add basic ioctl support for block devices

---

Makefile
arch/x64/arch-setup.cc
conf/profiles/x64/all.mk
conf/profiles/x64/base.mk
conf/profiles/x64/nvme.mk
core/debug.cc
drivers/nvme-queue.cc
drivers/nvme-queue.hh
drivers/nvme-structs.h
drivers/nvme.cc
drivers/nvme.hh
scripts/run.py

This patch implements the NVMe block device driver. It is greatly based on the pull request submitted by Jan Braunwarth (see https://github.com/cloudius-systems/osv/pull/1284) so most credit goes to Jan.
As his PR explains, OSv can be started with an emulated NVMe disk on QEMU like so:
`./scripts/run.py --nvme`
Compared to Jan's PR, this patch is different in the following ways:
- removes all non-NVMe changes (various bug fixes or ioctl enhancements are part of separate PRs)
- replaces most of the heap allocations by using stack which should reduce some contention
- tweaks PRP-handling code to use lock-less ring buffer which should further reduce contention when allocating memory
- fixes a bug in I/O queue CQ handling to correctly determine if SQ is not full
- assumes single namespace - 1 …

Implement NVMe driver

---

fs/rofs/rofs_vfsops.cc

The filesystem read and write operations call block device drivers `strategy()` function. The buffer argument of these functions needs to point to a contiguous area of physical memory because eventually the virtual address pointer will be converted to a physical one before being passed to the host layer.
Unfortunately, the logic in the ROFS mount that reads the master block and the i-node table uses regular `malloc()` to allocate buffers to read to. Everything works fine if the i-node table occupies less than 1 page (4K) on disk. But if it occupies more than 1 page of memory and underlying physical memory is fragmented one can experience errors like the one in the description of issue #1033.
This patch fixes this issue, by changing two `malloc()` calls with …

rofs: use contiguous buffer when reading i-node table

---

scripts/run.py

This patch eliminates the use of `losetup` in `run.py` when running OSv on Xen. Instead of creating a loop device pointing to qcow2 or raw image, run.py adds an entry to the xl config file pointing directly to the OSv disk image like so:
```disk=['/home/wkozaczuk/projects/osv/build/last/usr.img,qcow2,hda,rw']```
or:
```disk=['/home/wkozaczuk/projects/osv/build/last/usr.raw,raw,hda,rw']```
In addition, we also enhanced `run.py` to support 2nd disk when running OSv on Xen. Finally, when executing run.py with '--dry-run', one can see the content of the xl config file which can be useful for troubleshooting or manually running OSv using the xl utility.
Examples to run OSv on Xen:
```
./scripts/run.py -p xen #uses default qcow2 image build/last/usr.img
./scripts/run.py -nv -c 1 -p xen --script …
```

xen: stop using loop device in run.py

---

scripts/loader.py

It has been a while since we extracted the ZFS code from the kernel to build it as a shared library `libsolaris.so` that gets placed on the bootfs filesystem and loaded from there. For details see d7a627484b34aa8254d8fe444972aa18fe007ca7.
The command `osv syms` used when debugging and implemented in loader.py relies on the list of files that go into the image and is specified in `build/last/usr.manifest`. Unfortunately, `libsolaris.so` is not part of this manifest file but instead is part of `bootfs.manifest`. This causes the `osv syms` command to break as illustrated by #1324.
This patch fixes this by changing the Manifest class constructor to load information about files from both `bootfs.manifest` and `usr.manifest`.
This patch also fixes warnings about unescaped backslashes in the …

loader.py: fix 'osv syms' load bootfs.manifest

---

Makefile
bsd/sys/net/if_llatbl.cc
bsd/sys/net/radix.cc
bsd/sys/net/route.cc
bsd/sys/netinet/in.cc
bsd/sys/netinet/ip_icmp.cc
bsd/sys/netinet/ip_output.cc
conf/base.mk
core/callstack.cc
core/mmu.cc
core/net_trace.cc
include/lockfree/unordered_ring_mpsc.hh
include/osv/bitset-iter.hh
include/osv/callstack.hh
modules/golang/Makefile
modules/httpserver-api/Makefile
modules/httpserver-monitoring-api/Makefile
modules/sysinfo/Makefile
modules/tests/Makefile

This patch makes necessary changes to the relevant source files to make it possible to build kernel at C++ 17 level. This will allow us to take advantage of new features available in C++ 17 standard.
The following changes are part of this PR:
- remove obsolete `register` keyword (mostly under `bsd/` part of the tree)
- add `const` specifier to the comparison operator definitions where necessary
- replace deprecated `std::iterator` usage with explicit definitions of traits (for example `iterator_category`, `value_type`, and 3 others) (for some background info read this - https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/)
- add `constexpr` to the `friend` declaration of std::distance<mbuf_iterator>
- make tests, httpserver-api, and some other modules compilable with non-C++ 11 …

kernel: upgrade to C++ 17

---

scripts/run.py

The property virtio-blk-pci.scsi is deprecated since [QEMU 5.0](https://wiki.qemu.org/ChangeLog/5.0) and was removed in [QEMU 9.1](https://wiki.qemu.org/ChangeLog/9.1).
Since even before QEMU 5.0 the default value is false so I think this can be safely removed.
If we want to support QEMU < 2.5 I need to do something more complex here, because the default value was true back then.
See [here](https://patchew.org/QEMU/20210429155221.1226561-1-stefanha@redhat.com/) for more information
Closes #1340

bugfix/1340 run script for qemu >= 9.1

---

arch/aarch64/processor.hh

This patch fixes the bug described by #1354 where you can find more details.
In essence, we change the `arch::wait_for_interrupt()` called by `cpu::do_idle()` to reverse the order of the `wfi` instruction and the `msr daifclr, #2` that enables interrupts. As a result, when `arch::wait_for_interrupt()` is called, the following happens in this order:
- perform full system Data Synchronization Barrier
- enter low power 'Wait For Interrupt' mode
- execute the instruction barrier between 'wfi' and 'msr' to ensure they are executed in this order
- on exit from 'Wait For Interrupt' mode enable interrupts
This change guarantees that interrupts are not prematurely consumed before cpu enters the low-powered "wait for interrupt" mode. Instead, we let interrupts wake the cpu when in such mode and …

aarch64: do not enable interrupts before entering low-power standby state

---

drivers/nvme.cc
drivers/nvme.hh

The current NVMe driver initialization logic waits for the controller to become ready before trying to reset (aka disable) it. The NVMe specification does not mandate the initial state of the controller, and in some scenarios (like qemu on aarch64), the controller may be disabled, which leads to a timeout.
So this patch changes the driver initialization logic to skip waiting on the controller to become ready and instead simply reset it.
In addition, we also refactor the code by breaking `enable_disable_controller()` into more readable `reset_controller()` and `enable_controller()` methods.

nvme: do not assume controller is ready

---

arch/aarch64/pci.cc
arch/x64/pci.cc
drivers/pci-device.cc
drivers/pci-function.cc
drivers/pci-function.hh

This patch fixes three issues in the pci logic in the aarch64 port to support detecting and allocating msix bar:
- detect valid bars using its size (non-zero) instead of the value
- align the allocated bar address to its size
- detect pre-allocated bars
Firstly, on aarch64, unlike x86_64, the PCI BAR address is often not allocated (qemu virt). The current logic in `device::parse_pci_config()` skips any bars whose value is 0. This, unfortunately, prevents it from detecting msix bars with value 0. In essence, when an address is not allocated, only the bits 3-1 may be set for mmio bars. This means that 0 is a legitimate value and indicates a non-prefetchable 32-bits wide bar (see https://wiki.osdev.org/PCI#Base_Address_Registers). So on aarch64 at least we need to read the bar size to detect …

aarch64: support detecting and allocating msix bar

---

modules/tests/Makefile
tests/lib-circular-reloc1.cc
tests/lib-circular-reloc2.cc
tests/tst-elf-circular-reloc.cc

As suggested by @nyh, this adds a regression test case for the PR #1366, based on the minimal reproducer in this PR. With the patch from this PR applied, the `tst-elf-circular-reloc` test exits with a zero exit status. Without it, it fails to load with the ELF loader error message: “trying to execute or access missing symbol”.

tests: Add test case for circular ELF data relocations

---

Makefile
arch/aarch64/arch-dtb.cc
arch/aarch64/arch-dtb.hh
arch/aarch64/arch-setup.cc
arch/aarch64/exceptions.cc
arch/aarch64/exceptions.hh
arch/aarch64/gic-common.cc
arch/aarch64/gic-common.hh
arch/aarch64/gic-v2.cc
arch/aarch64/gic-v2.hh
arch/aarch64/gic-v3.cc
arch/aarch64/gic-v3.hh
arch/aarch64/msi.cc
conf/profiles/aarch64/all.mk
conf/profiles/aarch64/base.mk
conf/profiles/aarch64/nvme.mk
drivers/pci-function.cc
drivers/virtio-pci-device.cc

The series of these 4 commits implements the MSI support on the aarch64 architecture:
- Implement GIC v3 ITS and GIC v2m to support MSI
- Implement aarch64-specific MSI methods
- Enable MSI/X for virtio PCI devices
- Enable NVME support
Compared to the original PR, GIC v3 code does not use `std::map` and consistently employs spinlock with interrupts disabled in all necessary places.
For more details, please look at the commit messages.

Implement MSI support on the aarch64 architecture V2

---

core/elf.cc
include/osv/elf.hh
tests/tst-small-malloc.cc

Before this series, OSv fails to boot if built on Fedora 42 with Gcc 15.1.1.
It turns out the problem is symbol resolution during relocation of kernel symbols (specifically, TLS names like sched::s_current). Unfortunately we had two different copies of symbol resultion functions:
1. init_dyn_tabs::lookup() used for the initialization-time relocations.
2. object::lookup_symbol() used for any other lookups.
The latter is the complete implementation of symbol lookup, supporting both the traditional ELF "DT_HASH" hash table format, and the newer (2006) "DT_GNU_HASH" format. But the former implementation was incomplete, and was missing the DT_GNU_HASH support - so failed to do relocations (and boot...) on systems where DT_HASH was no longer output to the executable.
The first patch unifies …

init: fix boot when using DT_GNU_HASH

---

Makefile
bootfs_ext.manifest.skel
modules/libext/Makefile
modules/libext/module.py
modules/lwext4/module.py
modules/lwext4/usr.manifest
scripts/build
scripts/disk-utils-common.sh
scripts/ext-disk-utils.sh
scripts/zfs-image-on-host.sh
static/etc/fstab_ext
usr_ext.manifest.skel

This patch updates existing scripts and adds new `ext-disk-utils.sh` to support building OSv images with ext root filesystem.
More specifically, we update `scripts/build` to support new values of the parameter `fs`:
- `ext` - to build an image with the `ext` filesystem mounted at root (`/`)
- `rofs_with_ext` - to build an image with the `rofs` at `/` and `ext` in the 2nd disk partition mounted at `/data`
In addition, we add a new script `ext-disk-utils.sh`, called by `scripts/build`. The `ext-disk-utils.sh` utilizes the standard `mkfs.ext` utility from the Linux host to create an empty ext disk file, which is then set up as a loop device and mounted to populate its content using the `export_manifest.py`.
The `ext` filesystem is implemented as a library, similarly to the ZFZ. Just like …

support building ext images

---

modules/tests/Makefile
tests/tst-rwlock.cc

The tst-rwlock.hh included by tst-hub.cc implements rudimentary tests of the rwlock functionality. The misc-mutex.cc implements some basic performance tests around read and write aspects of the read-write lock.
This new tst-rwlock.cc facilates more elaborate testing of rwlock by allowing to simulate various workloads. Following options can be specified to adjust how the test is run:
- "readers" = number of reader threads (defaults to 1000)
- "writers" = number of writer threads (defaults to 10)
- "wloops" = number of loops each writer thread iterates over the data array inside the main loop (defaults to 1)
- "data_len" = size of the test array (defaults to 1000)
- "iterations" = number of times each reader and writer thread iterates in the main loop (defaults to 100)
- "wsleep" = should …

tests: add new rwlock unit test

---

modules/java-tests/Makefile

For Makefiles, we cannot assume that $SHELL is bash. Therefore, unless we set $SHELL explicitly, we must not use any non-POSIX bash language extensions. The `[[` operator is such a bash extension and causes the following output on Debian-derivates where /bin/sh is dash:
/bin/sh: 1: [: javac 1.8: unexpected operator
This commit fixes this by using POSIX's `[` operator.

tests: Fix bashism in java-tests Makefile
